Day 2: A jsem v prdeli, já nejím ryby! Je to tu!
antivirak/japonsko-vn pull request #44
Opened 2024-07-03 18:12 UTC by Elerenard

Ikonická hláška v akci!

2024-07-03 20:59 UTC, CaptainAgilek requested changes

2024-07-03 20:59 UTC, CaptainAgilek commented on game/story/akt3.rpy
> +    "A i tentokrát se vedení ujal Dante"
```suggestion
    "A i tentokrát se vedení ujal Dante."
```

2024-07-03 20:59 UTC, CaptainAgilek commented on game/story/akt3.rpy
> +    "svatyně byla zničena během druhé světové války při bombovém útoku na Tokio."
```suggestion
    "Svatyně byla zničena během druhé světové války při bombovém útoku na Tokio."
```

2024-07-03 20:59 UTC, CaptainAgilek commented on game/story/akt3.rpy
> +    d "Pojďte někam, kde můžete počkat, a já ho najdu."
```suggestion
    d "Pojďte někam, kde můžete počkat a já ho najdu."
```

2024-07-03 20:59 UTC, CaptainAgilek commented on game/story/akt3.rpy
> +    "Když jste zase všichni, oddechnete si, a jdete si koupit zmrzlinu,"
```suggestion
    "Když jste zase všichni, oddechnete si a jdete si koupit zmrzlinu,"
```

2024-07-03 20:59 UTC, CaptainAgilek commented on game/story/akt3.rpy
> +    "Pak jste se přesunuli na Šibuju, na jednu z co do počtu chodců, kteří ji denně používají největších křižovatek v Tokiu."
```suggestion
    "Pak jste se přesunuli na Šibuju, na jednu z největších křižovatek v Tokiu, co do počtu chodců, kteří ji denně používají."
```

2024-07-03 20:59 UTC, CaptainAgilek commented on game/story/akt3.rpy
> +    "A protože je čas oběda a Mimoň stále otravuje se suši, rozhodli jste se mu vyjít vstříc."
```suggestion
    "A protože je čas obědu a Mimoň stále otravuje se suši, rozhodli jste se mu vyjít vstříc."
```

2024-07-03 20:59 UTC, CaptainAgilek commented on game/story/akt3.rpy
> +    m "{\b} A jsem v prdeli, já nejím ryby! {\b}"
já byhc tu napsal možná něco že to Matěj chvíli zkoumal a pak to řekl :D

2024-07-03 21:03 UTC, antivirak commented on game/story/akt3.rpy
> +    d "Pojďte někam, kde můžete počkat, a já ho najdu."
Tady ta čárka asi bejt musí. To je poměr Hlavní věta -> vedlejší příslovečná místní, druhá Hlavní

2024-07-04 07:17 UTC, antivirak commented on game/story/akt3.rpy
> +    "Číšník postaví před vás tácy."
```suggestion
    "Číšník postaví před vás tácy."
    "Mimoň chvíli zkoumá svoji porci, zatímco vy se sborovým Itadakimas začínáte ochutnávat první kousky."  # TODO Mimoň si tam přines vlastní hůlky
```

2024-07-04 07:17 UTC, antivirak approved these changes

2024-07-04 07:18 UTC, merged